# Generated by Django 5.2.6 on 2025-12-04 05:06

import django.db.models.deletion
import pos_ecommerce.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_ecommerce', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('COMPRA', 'Ingreso por Compra'), ('VENTA', 'Salida por Venta'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('DEVOLUCION', 'Devolución'), ('TRANSFERENCIA_IN', 'Transferencia Entrada'), ('TRANSFERENCIA_OUT', 'Transferencia Salida')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity', models.IntegerField(validators=[pos_ecommerce.validators.validar_cantidad_positiva], verbose_name='Cantidad')),
                ('previous_stock', models.IntegerField(verbose_name='Stock Anterior')),
                ('new_stock', models.IntegerField(verbose_name='Stock Nuevo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pos_ecommerce.inventory', verbose_name='Inventario')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='pos_ecommerce.purchase', verbose_name='Compra Relacionada')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='pos_ecommerce.sale', verbose_name='Venta Relacionada')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
